name: onhighway
description: A flutter app for online services.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+7

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Language Support
    sdk: flutter

  cupertino_icons: ^1.0.2
  lint: ^1.0.0
  dio: ^4.0.0
  provider: ^5.0.0
  shared_preferences: ^2.0.6
  url_launcher: ^6.0.10
  razorpay_flutter: ^1.2.7
  google_maps_flutter: ^2.0.11
  map_picker: ^0.0.3
  flutter_svg: ^0.23.0+1
  geocoding: ^2.0.1
  geolocator: ^7.7.0
  firebase_messaging: ^11.4.2
  firebase_core: ^1.18.0
  flutter_local_notifications: ^8.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add images to your application, add an images section, like this:
  assets:
    - images/
    - assets/
