name: onhighway
description: A flutter app for online services.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+17

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Language Support
    sdk: flutter

  cupertino_icons: ^1.0.2
  lint: ^2.1.2
  dio: ^5.1.2
  provider: ^6.0.5
  shared_preferences: ^2.0.6
  url_launcher: ^6.0.10
  razorpay_flutter: ^1.2.7
  google_maps_flutter: ^2.0.11
  map_picker: ^0.0.3
  flutter_svg: ^2.0.6
  geocoding: ^2.0.1
  geolocator: ^9.0.2
  firebase_messaging: ^14.2.0
  firebase_core: ^2.4.0
  location: ^4.4.0
  flutter_local_notifications: ^13.0.0
  flutter_google_places: ^0.3.0
  font_awesome_flutter: ^10.3.0
  permission_handler: ^10.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true

  # To add images to your application, add an images section, like this:
  assets:
    - images/
    - assets/
